---
- name: "Check EnMasse artifact {{ enmasse_version }} exists"
  stat:
    path: "/tmp/enmasse-{{ enmasse_version }}.tgz"
  register: enmasse_artifact

- debug: msg="Using EnMasse artifact URL - {{ enmasse_download_url }}"

- name: "Retrieve EnMasse {{ enmasse_version }} artifact"
  get_url:
    url: "{{ enmasse_download_url }}"
    dest: "/tmp/enmasse-{{ enmasse_version }}.zip"
  when:
    enmasse_artifact.stat.exists == False

- name: Ensure tmp dir exists
  file:
    path: /tmp/enmasse-{{ enmasse_version }}
    state: directory

- name: Extract EnMasse artifact contents
  unarchive:
    src: "/tmp/enmasse-{{ enmasse_version }}.zip"
    dest: /tmp/enmasse-{{ enmasse_version }}

- set_fact:
    enmasse_playbook_location: enmasse-"{{ enmasse_version }}"/ansible/playbooks/openshift/deploy_all.yml
    enmasse_inventory_path: /tmp/enmasse-{{ enmasse_version }}/ansible/inventory/
  when: is_productised_version | bool  == False

- set_fact:
    enmasse_playbook_location: enmasse-"{{ enmasse_version }}"/amq-online-install/ansible/playbooks/openshift/deploy_all.yml
    enmasse_inventory_path: /tmp/enmasse-{{ enmasse_version }}/amq-online-install/ansible/inventory/
  when: is_productised_version | bool  == True

- name: Generate EnMasse inventory hosts file
  template:
    src: enmasse_hosts.j2
    dest: "{{ enmasse_inventory_path }}/hosts"

- name: Check EnMasse namespace for existing resources
  shell: oc get all -n {{ enmasse_namespace }}
  register: enmasse_resources_exist

- name: "Provision EnMasse {{ enmasse_version }}"
  shell: ansible-playbook -i {{ enmasse_inventory_path }}/hosts /tmp/{{enmasse_playbook_location}}
  args:
    chdir: "../"
  when: enmasse_resources_exist.stderr == "No resources found."

- name: "Verify EnMasse deployment succeeded"
  shell: sleep 5; oc get pods --namespace {{ enmasse_namespace }}  |  grep  "deploy"
  register: result
  until: not result.stdout
  retries: 50
  delay: 10
  failed_when: result.stdout
  changed_when: False

## Patch the keycloak deployment to use 1.2 image tag instead of latest
- copy:
  src: patch-enmasse-keycloak-image.json
  dest: /tmp/patch-enmasse-keycloak-image.json

- name: Store contents of enmasse keycloak image patch
  shell: cat /tmp/patch-enmasse-keycloak-image.json
  register: enmasse_keycloak_image_patch_content

- name: Patch enmasse keycloak to use 1.2 image tag
  shell: oc patch deployment/keycloak -p '{{ enmasse_keycloak_image_patch_content.stdout }}' -n {{ enmasse_namespace }}
  regiter: patch_kc_image
  changed_when: patch_kc_image.rc == 0

- name: "Verify patched deployments are ready"
  shell: sleep 5; oc get pods | awk '{print $2}' | grep '0/1'
  register: result
  until: not result.stdout
  retries: 50
  delay: 10
  failed_when: result.stdout
  changed_when: False

- name: Add labels to namespace
  shell: oc label --overwrite namespace {{ enmasse_namespace }} {{ monitoring_label_name }}={{ monitoring_label_value }} integreatly-middleware-service=true
  register: namespace_label
  failed_when: namespace_label.stderr != '' and 'not labeled' not in namespace_label.stderr
  changed_when: namespace_label.rc == 0

- name: Clean up EnMasse artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/enmasse-{{ enmasse_version }}.tgz
    - /tmp/enmasse-{{ enmasse_version }}.zip
    - /tmp/enmasse-{{ enmasse_version }}
  when: enmasse_clean_artifacts